### ISSUE TITLE
Instead of textbox add a list of radio buttons of category for description of the expense. 

### ISSUE THREAD

**Issue by rajeevbhat27** [rajeevbhat27/Xpense#2]
categories might be shopping, food, rent, bill etc..

**Comment by heykc** [comment]
Hi, do you want to replace description with just radio buttons for categories? or do you want to add categories along with description?

**Comment by rajeevbhat27** [comment]
Hello, replace textbox with radio buttons

**Comment by rajeevbhat27** [comment]
Hi, Instead of displaying all categories would it be possible to include these radio buttons in some list(something like dropdown )which will pop up at the time of choosing?
